let stackOfPlates = [];
stackOfPlates.push("red");
stackOfPlates.push("orange");
stackOfPlates.push("yellow");
stackOfPlates.push("green");
stackOfPlates.push("blue");
stackOfPlates.push("indigo");
stackOfPlates.push("violet");
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());
console.log(stackOfPlates.pop());